[package]
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.7.0"

[dependencies]
borsh = "0.10"
clap = "3.2.25"
serde = "1.0.164"
serde_derive = "1.0.130"
serde_json = "1.0.99"
solana-account-decoder = "=1.16.1"
solana-clap-utils = "=1.16.1"
solana-cli-config = "=1.16.1"
solana-cli-output = "=1.16.1"
solana-client = "=1.16.1"
solana-logger = "=1.16.1"
solana-program = "=1.16.1"
solana-remote-wallet = "=1.16.1"
solana-sdk = "=1.16.1"
spl-associated-token-account = { version = "=2.0", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-stake-pool = { version = "=0.7.0", path="../program", features = [ "no-entrypoint" ] }
spl-token = { version = "=4.0", path="../../token/program", features = [ "no-entrypoint" ]  }
bs58 = "0.4.0"
bincode = "1.3.1"

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
